basePath: /v1
definitions:
  handler.GeoPointDTO:
    properties:
      coordinates:
        items:
          type: number
        maxItems: 180
        minItems: -180
        type: array
      type:
        type: string
    required:
    - coordinates
    - type
    type: object
  handler.SearchDriverRequest:
    properties:
      limit:
        type: integer
      location:
        $ref: '#/definitions/handler.GeoPointDTO'
      radius:
        type: number
    required:
    - limit
    - location
    - radius
    type: object
  response.APIError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.SwaggerError:
    properties:
      error:
        $ref: '#/definitions/response.APIError'
      success:
        type: boolean
    type: object
  response.SwaggerSuccess:
    properties:
      code:
        type: string
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: Finds Nearest Driver According to User Point
  title: Macthing Driver API
  version: "1.0"
paths:
  /v1/driver-healthcheck:
    get:
      consumes:
      - application/json
      description: Checks if Driver Location API is up and running. Returns 200 OK
        with a success
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerSuccess'
      summary: Liveness probe
      tags:
      - system
  /v1/drivers/search:
    post:
      consumes:
      - application/json
      description: Returns drivers ordered by distance; distance (metres) is pre-calculated.
      parameters:
      - description: Search parameters
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.SearchDriverRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of DriverWithDistance
          schema:
            $ref: '#/definitions/response.SwaggerSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.SwaggerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerError'
      security:
      - InternalAuth: []
      summary: Find nearest drivers
      tags:
      - drivers
  /v1/healthz:
    get:
      consumes:
      - application/json
      description: Returns 200 OK with a success
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerSuccess'
      summary: Liveness probe
      tags:
      - system
securityDefinitions:
  InternalAuth:
    description: 'Internal calls only.  Format: "Bearer <token>"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
